name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Elke zondag om middernacht (Wekelijkse SAST scan)

jobs:
  build:
    name: Build and Test Python
    runs-on: ubuntu-latest

    permissions:
        actions: read
        contents: read
        security-events: write  # Nodig voor CodeQL upload
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No dependencies"

      - name: Run basic tests
        run: |
          echo "This is a test file content." > /tmp/file.txt  # Maak het bestand aan
          echo -e "pass\nHelloUser\nfile.txt\n1+1" | python app.py

      # SAST Scan
      - name: Static Application Security Testing with Bandit
        run: |
          python -m pip install bandit
          bandit -r . -ll

          
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.txt


      # Dependency Scanning
      - name: Dependency Check with pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          pip-audit

      # Secret Scanning with Gitleaks
      - name: Scan for Secrets
        uses: gitleaks/gitleaks-action@v2.3.7
        with:
          config-path: .github/workflows/gitleaks.toml
          fail: true  # Laat de pipeline falen bij gedetecteerde secrets
